FROM node:14
EXPOSE 44356

ARG NODE_ENV
ENV NODE_ENV $NODE_ENV

WORKDIR /app

RUN npm install -g nodemon

COPY package.json ./

RUN --mount=type=secret,id=npm,target=/root/.npmrc npm install

COPY . .

CMD ["npm","run","dev:container"]
