IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Role' AND COLUMN_NAME='Code')
  BEGIN
    ALTER TABLE Role
      ADD Code varchar(50) NULL

    EXEC('UPDATE Role SET Code = Id')

    ALTER TABLE Role
      ALTER COLUMN Code varchar(50) NOT NULL
  END