IF EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'dbo'
      AND TABLE_NAME = 'Role'
      AND COLUMN_NAME = 'Name'
      AND CHARACTER_MAXIMUM_LENGTH <> 250
)
BEGIN
    ALTER TABLE [dbo].[Role] ALTER COLUMN [Name] nvarchar(250) NOT NULL;
END
GO
